// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED_WEB_API_KEY',
    appId: '1:758004605511:web:6f9a29716370b559d60762',
    messagingSenderId: '758004605511',
    projectId: 'finly-23c1f',
    authDomain: 'finly-23c1f.firebaseapp.com',
    storageBucket: 'finly-23c1f.firebasestorage.app',
    measurementId: 'G-BW5DM1F684',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED_ANDROID_API_KEY',
    appId: '1:758004605511:android:b208b8db487f35e9d60762',
    messagingSenderId: '758004605511',
    projectId: 'finly-23c1f',
    storageBucket: 'finly-23c1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED_IOS_API_KEY',
    appId: '1:758004605511:ios:fb7062495bbb16aad60762',
    messagingSenderId: '758004605511',
    projectId: 'finly-23c1f',
    storageBucket: 'finly-23c1f.firebasestorage.app',
    iosBundleId: 'com.example.finly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REDACTED_IOS_API_KEY',
    appId: '1:758004605511:ios:fb7062495bbb16aad60762',
    messagingSenderId: '758004605511',
    projectId: 'finly-23c1f',
    storageBucket: 'finly-23c1f.firebasestorage.app',
    iosBundleId: 'com.example.finly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REDACTED_WEB_API_KEY',
    appId: '1:758004605511:web:d059ad4c611bf296d60762',
    messagingSenderId: '758004605511',
    projectId: 'finly-23c1f',
    authDomain: 'finly-23c1f.firebaseapp.com',
    storageBucket: 'finly-23c1f.firebasestorage.app',
    measurementId: 'G-MRS3VMJPCK',
  );
}
