part of 'app_theme.dart';

const _lightScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppLightColors.primary,
  onPrimary: AppLightColors.onPrimary,
  primaryContainer: AppLightColors.primaryContainer,
  onPrimaryContainer: AppLightColors.primaryDark,
  secondary: AppLightColors.secondary,
  onSecondary: Colors.white,
  secondaryContainer: AppLightColors.secondaryContainer,
  onSecondaryContainer: AppLightColors.secondary,
  surface: AppLightColors.surface,
  onSurface: AppLightColors.textPrimary,
  surfaceContainerHighest: AppLightColors.surfaceElevated,
  onSurfaceVariant: AppLightColors.textSecondary,
  outline: AppLightColors.border,
  outlineVariant: AppLightColors.border,
  error: AppLightColors.debit,
  onError: Colors.white,
  scrim: Colors.black54,
  inverseSurface: AppLightColors.textPrimary,
  onInverseSurface: AppLightColors.background,
  inversePrimary: AppLightColors.primaryDark,
);

const _darkScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.primary,
  onPrimary: AppColors.onPrimary,
  primaryContainer: AppColors.primaryContainer,
  onPrimaryContainer: AppColors.primary,
  secondary: AppColors.secondary,
  onSecondary: Colors.white,
  secondaryContainer: AppColors.secondaryContainer,
  onSecondaryContainer: AppColors.secondary,
  surface: AppColors.surface,
  onSurface: AppColors.textPrimary,
  surfaceContainerHighest: AppColors.surfaceElevated,
  onSurfaceVariant: AppColors.textSecondary,
  outline: AppColors.border,
  outlineVariant: AppColors.border,
  error: AppColors.debit,
  onError: Colors.white,
  scrim: Colors.black87,
  inverseSurface: AppColors.textPrimary,
  onInverseSurface: AppColors.background,
  inversePrimary: AppColors.primaryDark,
);
